<a href="https://colab.research.google.com/github/pavanrj3/algorithms-/blob/main/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_excel("/content/MTZpricelist (7).xlsx")

In [4]:
df.head()

,Unnamed: 0,Unnamed: 1,DESCRIPTION,UPC,PRICE,Avail,ORDER,TOTAL,TYPE,BRAND,Minimun Box Qty
0,1,100008,212 1.7 EDT M (100008) - Spain - 20pcs ByBox,8411061896259,34.25,16,NaN,NaN,100.Regular,CAROLINA HERRERA,20
1,2,100009,212 2.0 EDT L (100009) - Spain - 20pcs ByBox,8411061894026,35.75,188,NaN,NaN,100.Regular,CAROLINA HERRERA,20
2,3,119161,212 HEROES 1.7 EDT M (119161) - Spain - 1pcs ...,8411061974759,29.25,10,NaN,NaN,100.Regular,CAROLINA HERRERA,NaN
3,4,100051,212 VIP 3.4 EDT M (100051) - Spain - 15pcs ByBox,8411061088166,55.00,105,NaN,NaN,100.Regular,CAROLINA HERRERA,15
4,5,109348,212 VIP BLACK 3.4 EDP M (109348) - Spain - 15...,8411061043844,62.00,163,NaN,NaN,100.Regular,CAROLINA HERRERA,15

In [5]:
df.tail()

,Unnamed: 0,Unnamed: 1,DESCRIPTION,UPC,PRICE,Avail,ORDER,TOTAL,TYPE,BRAND,Minimun Box Qty
4133,4134,130073,OLAPLEX No.4C BOND MAINTENANCE CLARIFYING SHAM...,850018802765,13.50,60,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,12
4134,4135,130071,OLAPLEX No.4P BLONDE ENHACER TONING SHAMPOO 8....,850018802772,13.50,195,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,12
4135,4136,130079,OLAPLEX No.7 BONDING OIL 1.0 (130079) - USA -...,850045076085,13.25,999,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,24
4136,4137,127346,REN READY STEADY GLOW 8.5 TONIC TST - (127346...,5060389246975,10.00,6,NaN,NaN,115.Skincare and Cosmetics,UNDEFINED,NaN
4137,4138,131737,YSL LOVESHINE CANDY GLAZE 4 3.2G LIPSTICK (13...,4935421761758,21.00,177,NaN,NaN,115.Skincare and Cosmetics,YVES SAINT LAURENT,12

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4138 entries, 0 to 4137
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       4138 non-null   int64
 1   Unnamed: 1       4138 non-null   int64
 2   DESCRIPTION      4138 non-null   object
 3   UPC              4089 non-null   object
 4   PRICE            4138 non-null   float64
 5   Avail            4138 non-null   int64
 6   ORDER            0 non-null      float64
 7   TOTAL            0 non-null      float64
 8   TYPE             4138 non-null   object
 9   BRAND            4138 non-null   object
 10  Minimun Box Qty  3676 non-null   object
dtypes: float64(3), int64(3), object(5)
memory usage: 355.7+ KB

In [7]:
df.describe()

        Unnamed: 0     Unnamed: 1        PRICE        Avail  ORDER  TOTAL
count  4138.000000    4138.000000  4138.000000  4138.000000    0.0    0.0
mean   2069.500000  122689.335428    37.984222   404.863702    NaN    NaN
std    1194.682036    9697.102703    43.805255   371.975050    NaN    NaN
min       1.000000  100008.000000     0.000000     6.000000    NaN    NaN
25%    1035.250000  117115.500000    11.500000    72.000000    NaN    NaN
50%    2069.500000  125691.500000    22.000000   258.000000    NaN    NaN
75%    3103.750000  130475.250000    48.000000   754.750000    NaN    NaN
max    4138.000000  136758.000000   485.000000   999.000000    NaN    NaN

In [8]:
df.shape

(4138, 11)

In [9]:
df.isnull().sum()

Unnamed: 0            0
Unnamed: 1            0
DESCRIPTION           0
UPC                  49
PRICE                 0
Avail                 0
ORDER              4138
TOTAL              4138
TYPE                  0
BRAND                 0
Minimun Box Qty     462
dtype: int64

In [10]:
df.dropna()

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 1, DESCRIPTION, UPC, PRICE, Avail, ORDER, TOTAL, TYPE, BRAND, Minimun Box Qty]
Index: []

In [11]:
df.fillna(0)

,Unnamed: 0,Unnamed: 1,DESCRIPTION,UPC,PRICE,Avail,ORDER,TOTAL,TYPE,BRAND,Minimun Box Qty
0,1,100008,212 1.7 EDT M (100008) - Spain - 20pcs ByBox,8411061896259,34.25,16,0.0,0.0,100.Regular,CAROLINA HERRERA,20
1,2,100009,212 2.0 EDT L (100009) - Spain - 20pcs ByBox,8411061894026,35.75,188,0.0,0.0,100.Regular,CAROLINA HERRERA,20
2,3,119161,212 HEROES 1.7 EDT M (119161) - Spain - 1pcs ...,8411061974759,29.25,10,0.0,0.0,100.Regular,CAROLINA HERRERA,0
3,4,100051,212 VIP 3.4 EDT M (100051) - Spain - 15pcs ByBox,8411061088166,55.00,105,0.0,0.0,100.Regular,CAROLINA HERRERA,15
4,5,109348,212 VIP BLACK 3.4 EDP M (109348) - Spain - 15...,8411061043844,62.00,163,0.0,0.0,100.Regular,CAROLINA HERRERA,15
...,...,...,...,...,...,...,...,...,...,...,...
4133,4134,130073,OLAPLEX No.4C BOND MAINTENANCE CLARIFYING SHAM...,850018802765,13.50,60,0.0,0.0,115.Skincare and Cosmetics,OLAPLEX,12
4134,4135,130071,OLAPLEX No.4P BLONDE ENHACER TONING SHAMPOO 8....,850018802772,13.50,195,0.0,0.0,115.Skincare and Cosmetics,OLAPLEX,12
4135,4136,130079,OLAPLEX No.7 BONDING OIL 1.0 (130079) - USA -...,850045076085,13.25,999,0.0,0.0,115.Skincare and Cosmetics,OLAPLEX,24
4136,4137,127346,REN READY STEADY GLOW 8.5 TONIC TST - (127346...,5060389246975,10.00,6,0.0,0.0,115.Skincare and Cosmetics,UNDEFINED,0
4137,4138,131737,YSL LOVESHINE CANDY GLAZE 4 3.2G LIPSTICK (13...,4935421761758,21.00,177,0.0,0.0,115.Skincare and Cosmetics,YVES SAINT LAURENT,12

In [12]:
df.drop_duplicates()

,Unnamed: 0,Unnamed: 1,DESCRIPTION,UPC,PRICE,Avail,ORDER,TOTAL,TYPE,BRAND,Minimun Box Qty
0,1,100008,212 1.7 EDT M (100008) - Spain - 20pcs ByBox,8411061896259,34.25,16,NaN,NaN,100.Regular,CAROLINA HERRERA,20
1,2,100009,212 2.0 EDT L (100009) - Spain - 20pcs ByBox,8411061894026,35.75,188,NaN,NaN,100.Regular,CAROLINA HERRERA,20
2,3,119161,212 HEROES 1.7 EDT M (119161) - Spain - 1pcs ...,8411061974759,29.25,10,NaN,NaN,100.Regular,CAROLINA HERRERA,NaN
3,4,100051,212 VIP 3.4 EDT M (100051) - Spain - 15pcs ByBox,8411061088166,55.00,105,NaN,NaN,100.Regular,CAROLINA HERRERA,15
4,5,109348,212 VIP BLACK 3.4 EDP M (109348) - Spain - 15...,8411061043844,62.00,163,NaN,NaN,100.Regular,CAROLINA HERRERA,15
...,...,...,...,...,...,...,...,...,...,...,...
4133,4134,130073,OLAPLEX No.4C BOND MAINTENANCE CLARIFYING SHAM...,850018802765,13.50,60,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,12
4134,4135,130071,OLAPLEX No.4P BLONDE ENHACER TONING SHAMPOO 8....,850018802772,13.50,195,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,12
4135,4136,130079,OLAPLEX No.7 BONDING OIL 1.0 (130079) - USA -...,850045076085,13.25,999,NaN,NaN,115.Skincare and Cosmetics,OLAPLEX,24
4136,4137,127346,REN READY STEADY GLOW 8.5 TONIC TST - (127346...,5060389246975,10.00,6,NaN,NaN,115.Skincare and Cosmetics,UNDEFINED,NaN
4137,4138,131737,YSL LOVESHINE CANDY GLAZE 4 3.2G LIPSTICK (13...,4935421761758,21.00,177,NaN,NaN,115.Skincare and Cosmetics,YVES SAINT LAURENT,12

In [13]:
df.duplicated().sum()

np.int64(0)